server:
  port: 6970

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mcdonalddylan/RedactedConfigServer
          clone-on-start: true